const crypto = require('crypto');
const fs = require('fs');
const password = process.env.DECRYPT_PSSWD;
const data = fs.readFileSync('raw_creds.json');
const salt = data.slice(8, 16);
const encrypted = data.slice(16);
const keyiv = crypto.pbkdf2Sync(password, salt, 100000, 48, 'sha256');
const key = keyiv.slice(0, 32);
const iv  = keyiv.slice(32, 48);
const decipher = crypto.createDecipheriv('aes-256-cbc', key, iv);
const decrypted = Buffer.concat([decipher.update(encrypted), decipher.final()]);
fs.writeFileSync('decrypted_creds.json', decrypted);
console.log('Decrypted successfully');
